### ISSUE TITLE
trouble with installing 

### ISSUE THREAD

**Issue by AlexandrMiroshnikov** [BioComputingUP/ring-pymol#1]
Hello! I tried to install your plugin on Windows and on Linux Mint. On windows I get error "Can't import name "cached_property" ////functools.py On Linux I see this:   File "/usr/lib/python3/dist-packages/pymol/plugins/legacysupport.py", line 159, in __getattr__
    import tkinter.messagebox as module
ModuleNotFoundError: No module named 'tkinter'
Can you help me, please?

**Comment by AlessioDelConte** [comment]
Hello,
I recommend you to use a linux system for the installation of the plugin in PyMOL. Regarding the error I think you will need to install tkinter with `pip install tk` if you are using pip, or `conda install -c anaconda tk` fi you are using conda.
Please note that this is not a final release and it will be update soon.

**Comment by AlexandrMiroshnikov** [comment]
Hello! Thanks, for reply. I will try it.

ср, 25 мая 2022 г., 15:24 Alessio Del Conte ***@***.***>:

**Comment by AlexandrMiroshnikov** [comment]
Hello, I've installed "tk", but error is still here. No module named 'tkinter'

**Comment by AlessioDelConte** [comment]
You have to install the python module in the python that pymol is using.
How did you installed pymol?

Il Ven 27 Mag 2022, 05:59 AlexandrMiroshnikov ***@***.***> ha
scritto:

**Comment by AlexandrMiroshnikov** [comment]
I downloaded pymol from official cite.

**Comment by AlessioDelConte** [comment]
Then you have to install all the python libraries listed in the readme with
the bundled python shipped with pymol

Il Ven 27 Mag 2022, 08:14 AlexandrMiroshnikov ***@***.***> ha
scritto:

**Comment by AlexandrMiroshnikov** [comment]
Ok, thanks.

пт, 27 мая 2022 г. в 13:27, Alessio Del Conte ***@***.***>:
