### ISSUE TITLE
MacOS installation?

### ISSUE THREAD

**Issue by visvaldask** [BioComputingUP/ring-pymol#3]
Are there some version requirements? I guess it's more of a pymol problem, because on MacOS I was not able to launch pymol  (opensource version) because of this error, after I installed pymol.

(ringpymol) {visvaldas}~% /Users/visvaldas/miniconda3/envs/ringpymol/bin/pymol
 PyMOL(TM) Molecular Graphics System, Version 2.5.0.
 Copyright (c) Schrodinger, LLC.
 All Rights Reserved.
 
    Created by Warren L. DeLano, Ph.D. 
 
    PyMOL is user-supported open-source software.  Although some versions
    are freely available, PyMOL is not in the public domain.
 
    If PyMOL is helpful in your work or study, then please volunteer 
    support for our ongoing efforts to create open and affordable scientific
    software by purchasing a PyMOL Maintenance and/or Support subscription.

    More information can be found at "http://www.pymol.org".
 
    Enter "help" for a list of commands.
    Enter "help <command-name>" for information on a specific command.

 Hit ESC anytime to toggle between text and graphics.

 Detected OpenGL version 2.1. Shaders available.
 Detected GLSL version 1.20.
 OpenGL graphics engine:
  GL_VENDOR:   Intel Inc.
  GL_RENDERER: Intel(R) Iris(TM) Plus Graphics 645
  GL_VERSION:  2.1 INTEL-20.5.7
2023-05-01 17:14:20.312 python[45615:15686367] -[QNSApplication macOSVersion]: unrecognized selector sent to instance 0x7fd0fbbf1f20
2023-05-01 17:14:20.319 python[45615:15686367] *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[QNSApplication macOSVersion]: unrecognized selector sent to instance 0x7fd0fbbf1f20'
*** First throw call stack:
(
	0   CoreFoundation                      0x00007ff806a571ba __exceptionPreprocess + 242
	1   libobjc.A.dylib                     0x00007ff80657d42b objc_exception_throw + 48
	2   CoreFoundation                      0x00007ff806af301f -[NSObject(NSObject) __retain_OA] + 0
	3   CoreFoundation                      0x00007ff8069c28d7 ___forwarding___ + 1392
	4   CoreFoundation                      0x00007ff8069c22d8 _CF_forwarding_prep_0 + 120
	5   libtk8.6.dylib                      0x00000001148e94f2 GetRGBA + 50
	6   libtk8.6.dylib                      0x00000001148e93ea TkpGetColor + 490
	7   libtk8.6.dylib                      0x00000001148227c9 Tk_GetColor + 153
	8   libtk8.6.dylib                      0x00000001148121b6 Tk_Get3DBorder + 134
	9   libtk8.6.dylib                      0x000000011481201f Tk_Alloc3DBorderFromObj + 127
	10  libtk8.6.dylib                      0x0000000114823d22 DoObjConfig + 994
	11  libtk8.6.dylib                      0x0000000114823825 Tk_InitOptions + 357
	12  libtk8.6.dylib                      0x0000000114823705 Tk_InitOptions + 69
	13  libtk8.6.dylib                      0x0000000114854e8c CreateFrame + 1548
	14  libtk8.6.dylib                      0x0000000114855167 TkListCreateFrame + 151
	15  libtk8.6.dylib                      0x000000011484cc08 Initialize + 2168
	16  _tkinter.cpython-311-darwin.so      0x000000011448372b Tcl_AppInit + 91
	17  _tkinter.cpython-311-darwin.so      0x0000000114483419 Tkapp_New + 585
	18  _tkinter.cpython-311-darwin.so      0x00000001144831be _tkinter_create_impl + 222
	19  _tkinter.cpython-311-darwin.so      0x0000000114482dc6 _tkinter_create + 182
	20  python3.11                          0x00000001006dd62d cfunction_vectorcall_FASTCALL + 93
	21  python3.11                          0x00000001007d1299 _PyEval_EvalFrameDefault + 235881
	22  python3.11                          0x00000001006785df _PyFunction_Vectorcall + 511
	23  python3.11                          0x000000010067ac30 _PyObject_Call_Prepend + 192
	24  python3.11                          0x000000010070d297 slot_tp_init + 183
	25  python3.11                          0x00000001007011ca type_call + 122
	26  python3.11                          0x00000001007d1437 _PyEval_EvalFrameDefault + 236295
	27  python3.11                          0x00000001006785df _PyFunction_Vectorcall + 511
	28  python3.11                          0x00000001006893b6 property_descr_get + 134
	29  python3.11                          0x00000001006e47b9 PyObject_GenericGetAttr + 585
	30  python3.11                          0x00000001007bdb92 _PyEval_EvalFrameDefault + 156258
	31  python3.11                          0x0000000100794f6d _PyEval_Vector + 493
	32  python3.11                          0x0000000100794d0a PyEval_EvalCode + 250
	33  python3.11                          0x000000010079015b builtin_exec + 379
	34  python3.11                          0x00000001006dd59f cfunction_vectorcall_FASTCALL_KEYWORDS + 95
	35  python3.11                          0x00000001007d80cf _PyEval_EvalFrameDefault + 264095
	36  python3.11                          0x00000001006785df _PyFunction_Vectorcall + 511
	37  python3.11                          0x0000000100675bac _PyObject_VectorcallTstate.752 + 60
	38  python3.11                          0x000000010067cc07 object_vacall + 407
	39  python3.11                          0x000000010067ca12 PyObject_CallMethodObjArgs + 226
	40  python3.11                          0x00000001008193ab PyImport_ImportModuleLevelObject + 3227
	41  python3.11                          0x000000010078e991 builtin___import__ + 289
	42  python3.11                          0x00000001006dd59f cfunction_vectorcall_FASTCALL_KEYWORDS + 95
	43  python3.11                          0x00000001007d1299 _PyEval_EvalFrameDefault + 235881
	44  python3.11                          0x00000001006785df _PyFunction_Vectorcall + 511
	45  python3.11                          0x00000001007d80cf _PyEval_EvalFrameDefault + 264095
	46  python3.11                          0x0000000100794f6d _PyEval_Vector + 493
	47  python3.11                          0x0000000100794d0a PyEval_EvalCode + 250
	48  python3.11                          0x0000000100844e87 run_mod + 167
	49  python3.11                          0x0000000100844c95 pyrun_file + 133
	50  python3.11                          0x0000000100844763 _PyRun_SimpleFileObject + 275
	51  python3.11                          0x000000010084410f _PyRun_AnyFileObject + 143
	52  python3.11                          0x0000000100868f3b pymain_run_file_obj + 267
	53  python3.11                          0x00000001008689b5 pymain_run_file + 85
	54  python3.11                          0x000000010086833c Py_RunMain + 1964
	55  python3.11                          0x0000000100607528 main + 56
	56  dyld                                0x00007ff8065aa41f start + 1903
)
libc++abi: terminating due to uncaught exception of type NSException
Abort

The schrodinger version I was not even able to install using conda:

UnsatisfiableError: The following specifications were found to be incompatible with each other:

Output in format: Requested package -> Available versions

I do have a working pymol installed via macports, but RING fails to launch with error message No module named 'qt_material'

Should I try installing lower pymol versions via conda?

Best regards,

Vis

**Comment by AlessioDelConte** [comment]
Hi Vis,

There is a requirement for a PyMOL version >= 2.5.0, but from what I see you already satisfied it.
How did you installed this PyMOL version?
To install it via conda I recommend you following the instruction on the README of this project, creating a new environment from the YAML file, plus this environment already installs all the required dependencies for the RING plugin.

Best,
Alessio

**Comment by visvaldask** [comment]
I tried installing via ylm file, and pymol crashes because of the same error as above. Clearly, it's a pymol problem, because if I try to install pymol-open-source default install via conda (that is no ring installation), pymol crashes still the same. I don't know how macports manages to install pymol that doesn't crash. Too bad I have to use conda's pymol, not macports version...

Thank you,
Vis
