### ISSUE TITLE
"no such file or directory: '/tmp/tmp374jfdsld'" |  set working dir in ring-plugin

### ISSUE THREAD

**Issue by mhoppe-cau** [BioComputingUP/ring-pymol#7]
Hi,
how can i set the working directory inside of the plugin?
i installed the plugin as recommended via conda. but when i want to use it, i have to change the working directory of pymol to the temporary directory created by the ring-plugin.
thx in advance!
kind regards from Kiel
Mathias

**Comment by AlessioDelConte** [comment]
Hi, 
can you give me some more information about your system where you are running PyMOL and if you are using the local version of RING or the API calls?

**Comment by mhoppe-cau** [comment]
Hi Alessio,
fast reply! nice! :)
we are using a local version on ubuntu with kernel 6.2.0-26 (22.04. desktop),
i used the  "Conda YAML (RECOMMENDED)." installation path
kr
mathias

**Comment by AlessioDelConte** [comment]
Ok it should be fine.
It is strange that you have to change directory when using the plugin. When does the error occur? When starting the RING computation?

**Comment by mhoppe-cau** [comment]
alessio, i am sorry. i juste realised the error only occure when i open the plugin before loading the pdb in pymol.
in fact, i could start the computation, but the visualisation failed, becasue pymol was not set to the right working directory. 
I just set the WD to the home dir, and saved this config in pymol. now everything works fine!
sorry for bothering you and big thumbs up for the fast response!

**Comment by AlessioDelConte** [comment]
No problem,
Thanks!
