### ISSUE TITLE
problem with running ring locally

### ISSUE THREAD

**Issue by marti-C20** [BioComputingUP/ring-pymol#8]
Hi, when I try to run the plugin locally, I obtain this error OSError: [Errno 8] Exec format error: ‘/mypath/ring-3.0.0/ring/bin/ring'
I’ve already added the path to the $PATH environment variable but I still obtain the error, even trying to run ring from the terminal I get something similar (zsh: exec format error: ring). I’m currently working with a MacBook Air M1 macOS Sonoma. Any suggestion?

**Comment by AlessioDelConte** [comment]
Hi, which version of ring are you using? Are you sure you requested the version compiled for mac os?

**Comment by marti-C20** [comment]
v3.0, I'm sorry I just requested ring 3 without specifying anything on the website. I thought it was already the correct version. I will make a new request asking for a mac version, thank you.
