### ISSUE TITLE
Trouble during installation

### ISSUE THREAD

**Issue by marti-C20** [BioComputingUP/ring-pymol#9]
After installing PyMOL and all the dependencies, I am having trouble in installing the plugin in PyMOL - Plugin Manager. In installing from repository and adding https://ring.biocomputingup.it/plugin/, there is no ring-plugin.zip folder in the right panel but something like:

<!doctype html>
<html lang="en" data-critters-container>
<head>
   etc.

Is there a different way to install the plugin?

**Comment by AlessioDelConte** [comment]
Hi,

yes, the file was moved on https://old.ring.biocomputingup.it/plugin/ as we are rolling out a new version of RING and of the plugin
